### ISSUE TITLE
Crashes on directory creation failure

### ISSUE THREAD

**Issue by gunnbr** [BOLL7708/OpenVR2Key#15]
I installed this program by putting it in my Program Files\OpenVR2Key directory, then ran it as a normal user. When I tried to create a binding, the app crashed. Event viewer shows this:
```Application: OpenVR2Key.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.UnauthorizedAccessException
   at System.IO.__Error.WinIOError(Int32, System.String)
   at System.IO.Directory.InternalCreateDirectory(System.String, System.String, System.Object, Boolean)
   at System.IO.Directory.InternalCreateDirectoryHelper(System.String, Boolean)
   at OpenVR2Key.MainModel.StoreConfig(System.Collections.Generic.Dictionary`2<System.String,System.Windows.Input.Key[]>, System.String)
   at OpenVR2Key.MainModel.RegisterBinding(System.String, System.Collections.Generic.HashSet`1<System.Windows.Input.Key>)
   at OpenVR2Key.MainController.ToggleRegisteringKey(System.String, System.Object, System.Object ByRef)
   at OpenVR2Key.MainWindow.Label_RecordSave_Click(System.Object, System.Windows.Input.MouseButtonEventArgs)
   at System.Windows.RoutedEventArgs.InvokeHandler(System.Delegate, System.Object)
   at System.Windows.RoutedEventHandlerInfo.InvokeHandler(System.Object, System.Windows.RoutedEventArgs)
   at System.Windows.EventRoute.InvokeHandlersImpl(System.Object, System.Windows.RoutedEventArgs, Boolean)
   at System.Windows.UIElement.RaiseEventImpl(System.Windows.DependencyObject, System.Windows.RoutedEventArgs)
   at System.Windows.UIElement.RaiseTrustedEvent(System.Windows.RoutedEventArgs)
   at System.Windows.Input.InputManager.ProcessStagingArea()
   at System.Windows.Input.InputManager.ProcessInput(System.Windows.Input.InputEventArgs)
   at System.Windows.Input.InputProviderSite.ReportInput(System.Windows.Input.InputReport)
   at System.Windows.Interop.HwndMouseInputProvider.ReportInput(IntPtr, System.Windows.Input.InputMode, Int32, System.Windows.Input.RawMouseActions, Int32, Int32, Int32)
   at System.Windows.Interop.HwndMouseInputProvider.FilterMessage(IntPtr, MS.Internal.Interop.WindowMessage, IntPtr, IntPtr, Boolean ByRef)
   at System.Windows.Interop.HwndSource.InputFilterMessage(IntPtr, Int32, IntPtr, IntPtr, Boolean ByRef)
   at MS.Win32.HwndWrapper.WndProc(IntPtr, Int32, IntPtr, IntPtr, Boolean ByRef)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(System.Object)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(System.Delegate, System.Object, Int32)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(System.Object, System.Delegate, System.Object, Int32, System.Delegate)
   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(System.Windows.Threading.DispatcherPriority, System.TimeSpan, System.Delegate, System.Object, Int32)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr, Int32, IntPtr, IntPtr)
   at MS.Win32.UnsafeNativeMethods.DispatchMessage(System.Windows.Interop.MSG ByRef)
   at System.Windows.Threading.Dispatcher.PushFrameImpl(System.Windows.Threading.DispatcherFrame)
   at System.Windows.Application.RunDispatcher(System.Object)
   at System.Windows.Application.RunInternal(System.Windows.Window)
   at OpenVR2Key.App.Main()
```

I was able to work around the problem by running it as admin, which allowed it to create the directory, but it would be nice if the app didn't crash with no explanation when directory creation fails.

**Comment by BOLL7708** [comment]
Honestly didn't know it would be an issue as I'm always running it out of my bin folder, and as I don't publish with an installer I didn't really look into access levels, whelp. 😅 Thanks for pointing it out though, I'll try to recreate this and see what can be done when I have time to update this again.

A related question, can you after the folder has been created run it without administrator access?

**Comment by gunnbr** [comment]
Yes. After the folder was created, I was able to run it as a normal user and the bindings I had set in admin mode worked fine.

**Comment by BOLL7708** [comment]
As I've been working on other projects I haven't made a program feature to solve this, when reading about this it is recommended to create the folder in the installer, and I am not using an installer. Due to this I've tried to solve it by now including an empty folder in the release archive, I hope this will be a fix. If not feel free to re-open the issue.
